version: '3.3'

services:
    nginx:
        build:
            context: .
            dockerfile: docker/Nginx.Dockerfile
        ports:
            - 8098:80
        volumes:
            - ./:/var/www/app
        links:
            - fpm
    fpm:
        build:
            context: .
            dockerfile: docker/Phpfpm.Dockerfile
        volumes:
            - ./:/var/www/app
        links:
            - mysql
    mysql:
        image: mysql:8.0
        ports: 
            - 3309:3306
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=casino
        
